language: ruby
rvm:
  - 2.0.0
branches:
  only:
    - master
install:
  - bundle install
script:
  - set -e
  - git config --global user.email "test@example.com"
  - git config --global user.name "Test"
  - rake
  - ./test.sh

