language: ruby
os:
  - linux
  - osx
rvm:
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - ruby-head
install:
  - gem update --system && gem install bundler && bundle install
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
script:
  - set -e
  - git config --global user.email "test@example.com"
  - git config --global user.name "Test"
  - rake
  - ./test.sh
