language: ruby
rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - ruby-head
branches:
  only:
    - master
install:
  - gem update --system
  - bundle install
matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
script:
  - set -e
  - git config --global user.email "test@example.com"
  - git config --global user.name "Test"
  - rake
  - ./test.sh
